# Generated by Django 4.1.7 on 2023-03-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_project_vote_ratio_alter_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='vote_ratio',
            field=models.IntegerField(blank='True', default=0, max_length=2, null='True'),
        ),
    ]
