# Generated by Django 4.1.7 on 2023-03-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0008_alter_student_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
